[workspace]
members = ["pg-core", "pg-cli", "pg-pkg", "pg-wasm"]
default-members = ["pg-core", "pg-cli", "pg-pkg"]

resolver = "2"

[profile.release]
lto = true

[profile.release.package.pg-wasm]
opt-level = "s"
